name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@dda699c5656ae92f208b052fc91193a8423fffa6 # v3
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: pboling
          abortIfPreviousAssignees: true
          allowSelfAssign: true
          numOfAssignee: 1